### ISSUE TITLE
安装readme.md中步骤部署 大佬你的项目 发现无法访问前端页面

### ISSUE THREAD

**Issue by Qing1** [wujunwei928/parse-video-py#1]
抱歉 大佬好 第一次构建docker项目
 
 第一步 从 GitHub拉取项目到本地 使用vscode 打开
![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/4663a7ae-1fc5-4470-88bf-d6b8ef111663)

第二部 按照readme.md提示 
安装依赖 pip install -r requirements.txt
接着安装了docker
运行 docker pull wujunwei928/parse-video-py
![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/2907ab29-6501-48fd-8231-2916958ee85b)
随后运行命令docker run -d -p 8000:8000 wujunwei928/parse-video
![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/c9a6b40f-1339-4efd-aa9d-eb19ad17d7c8)
此时 打开 前端页面http://127.0.0.1:8000/

![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/3524cf70-ed16-4b11-badb-752bb187b05f)

请问 大佬是哪里的问题呢

同样的步骤 我在宝塔面板里也尝试了一下
然后访问 我的公网IP:8000
发现也不行

![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/bb585d27-01ac-44f9-a23d-33721e7613b5)

请问 作者 ，我是不是 哪里做错了

**Comment by wujunwei928** [comment]
不好意思, readme文档中 docker run 命令的 镜像名字写错了(写成go版本的镜像名了,两个端口不一样),  
已更新readme, 正确应该是 docker run -d -p 8000:8000 wujunwei928/parse-video-py

**Comment by Qing1** [comment]
谢谢大佬 头一次搞这个  嗯 这样确实可以的
