### ISSUE TITLE
py版本怎么修改端口。

### ISSUE THREAD

**Issue by duiaic** [wujunwei928/parse-video-py#21]
![QQ浏览器截图20241109171733](https://github.com/user-attachments/assets/de0a189e-a948-4cf9-bea9-241477866176)

我已经修改main文件里的端口号了。启动项目还是8000端口

**Comment by wujunwei928** [comment]
看你截图, 没有截取启动命令, 不确定你用的哪种方法启动

可以用下面三种方法变换端口启动
1. 修改 main.py 中的port, 直接 python 启动
```shell
python main.py
```

2. uvicorn 命令行修改端口启动
```shell
uvicorn main:app --host 0.0.0.0 --port 8080
```

3. docker 将8000映射到其他端口启动
```shell
sudo docker run -p 8888:8000 wujunwei928/parse-video-py
```

**Comment by wujunwei928** [comment]
2, 3两种方法无需修改main.py文件

**Comment by wujunwei928** [comment]
2, 3两种方法无需修改main.py文件
