### ISSUE TITLE
大佬请问怎么添加其他的参数

### ISSUE THREAD

**Issue by duiaic** [wujunwei928/parse-video-py#22]
首先感谢大哥在上一个问题的解答。已经可以修改端口了。

这次的问题是，比如说我需要输出视频的上传时间，还有视频的点赞数，评论数，等等。我试着添加但是都报错，不知道怎么回事，劳烦大哥空闲的时候解答一下。谢谢。

**Comment by wujunwei928** [comment]
![image](https://github.com/user-attachments/assets/209800a0-4cb2-4987-8381-dd6107e081ab)
目前只支持这些字段, 如果需要其他字段, 可以fork自己开发, 确认接口中是否有返回相关字段

可以 `parser/base.py` 中 `VideoInfo` 类 添加相关字段, 字段给默认值, 各个渠道parser从接口返回 json 或 html 中解析中解析字段进行赋值

**Comment by duiaic** [comment]
好的，谢谢了。
