### ISSUE TITLE
皮皮虾提取不到了

### ISSUE THREAD

**Issue by ymgcs** [wujunwei928/parse-video-py#27]
好像是那个接口挂了。大佬有没有解决办法

**Comment by mxccdd** [comment]
视频用：https://h5.pipix.com/bds/cell/cell_h5_comment/?cell_type=1&aid=1319&app_name=super&cell_id={video_id}
图集用：https://h5.pipix.com/bds/webapi/item/detail/?cell_type=1&aid=1319&app_name=super&item_id={video_id}
