### ISSUE TITLE
快手图集 识别有误

### ISSUE THREAD

**Issue by Qing1** [wujunwei928/parse-video-py#4]
**快手图集** 基本识别正常 
       但在遇到一种 上下滑动的图集时候 识别张数多了
       实际是13张图，具体测试图集链接如下：https://v.kuaishou.com/EYhNCZ 超级好看的全屏壁纸，把亮度调到最高 "超好看的背景图 "请礼貌拿图谢谢 该作品在快手被播放过24.8万次，点击链接，打开【快手】直接观看！
  
  **个人测试部署网站**   https://daohang.bxmang.top/vp/
  

![Snipaste_2024-05-18_16-48-55](https://github.com/wujunwei928/parse-video-py/assets/13379037/58ffb035-d544-438b-8e54-3b18391b274d)

**Postman测试**结果如下 https://daohang.bxmang.top/vp/video/share/url/parse?url=encodeURIComponent(https://v.kuaishou.com/EYhNCZ )

![Snipaste_2024-05-18_16-54-27](https://github.com/wujunwei928/parse-video-py/assets/13379037/97c24e8c-dc49-49f4-88c3-ab0400da8a8d)

      登上GitHub后 非常开心看到大佬更新了 快手图集功能  在网站部署后 因为网址已经部署了其他的项目 所以，修改了请求头 ，多加了 vp后缀  再加上我是小白玩家 代码基本靠Kimi  所以 Nginx  设置如下
![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/7b52754e-e172-4de7-b0f9-becd128fdb66)
 
 实际使用时，发现需要简单修改index.html 的请求  当然 大佬也可以也可以说下别的修改方法 我全是全靠蒙，哪疼医哪
 
![image](https://github.com/wujunwei928/parse-video-py/assets/13379037/bf10c9e7-0956-48b0-97ad-3a72c11e97f3)

  部署完成就是  https://daohang.bxmang.top/vp/ 
  
  测试发现的**第二个问题**是 实际解析链接可以获得 但在具体下载视频时候 总是403 Forbidden,   这具体是什么原因 有解决办法吗  当然按照提示文字 复制链接 打开网页 确实可以解决该问题 
  
   实际在看代码时候 发现结构好强  好优雅 大赞

**Comment by wujunwei928** [comment]
1. 用自带的那个index.html的话, 用你这种修改方法就可以, 现在就是优先使用AI工具, 快速解决问题就行, 我也经常用chatgpt, kimi
2. 图集解析没问题, 接口返回就是这样, 视频中看着是一张, 应该是因为两张图片刚好挨着, 看着像一张
![image](https://github.com/wujunwei928/parse-video-py/assets/3396697/d7d79beb-c83a-46d6-b9fd-8cfaf938ff8a)
3. 显示 403 Forbidden, 是因为有些网站有防盗链, 检测到访问的refer网址不是自己网站, 就不允许访问, 可以在 下载视频 按钮, 右键复制链接地址, 新开浏览器标签页打开即可
![image](https://github.com/wujunwei928/parse-video-py/assets/3396697/2401600d-4c89-4989-83de-24478ad7eda8)

**Comment by Qing1** [comment]
![QQ图片20240519154723](https://github.com/wujunwei928/parse-video-py/assets/13379037/033b1375-8eb4-4736-af72-6a128c223206)

 谢谢大佬解答。 上面这张图片是手机上保存时候的样子：图片是没有分开的。但网页上返回的数据看了 确实是16个，确实是3个被平台分割了  。
 
 这个我能想到的办法 就是后期提供一个图片拼接的服务 让用户自己选择拼接合并 或者 识别图片高度  提示用户合并图片，但感觉这个拼接服务会比较难，我先找下解决方法。
